QJsonChannel: QJsonChannelServiceRepository Class Reference
QJsonChannelServiceRepository Class Reference
The main entity of QJsonChannel represents service repository and provides API for a JSON-RPC method invokation.
#include <QJsonChannelServiceRepository.h>
Public Member Functions
QJsonChannelServiceRepository ()
~QJsonChannelServiceRepository ()
bool addService (QJsonChannelService *service)
Adds service to the repository.
bool addService (const QByteArray &name, const QByteArray &version, const QByteArray &description, QObject *obj)
Adds service to the repository.
QJsonChannelService * getService (const QByteArray &serviceName)
Return service by name.
QObject * getServiceObject (const QByteArray &serviceName)
Return service object by name.
bool removeService (QJsonChannelService *service)
Removes service from the repository.
bool removeService (const QByteArray &serviceName)
Removes service from the repository.
QJsonChannelMessage processMessage (const QJsonChannelMessage &message)
Process a JSON-RPC message. In general it means the invogation of a requested function of a requested service.
Detailed Description
The main entity of QJsonChannel represents service repository and provides API for a JSON-RPC method invokation.
Definition at line 15 of file QJsonChannelServiceRepository.h.
Constructor & Destructor Documentation
QJsonChannelServiceRepository()
QJsonChannelServiceRepository::QJsonChannelServiceRepository ()
Definition at line 27 of file QJsonChannelServiceRepository.cpp.
                                                               : d (new QJsonChannelServiceRepositoryPrivate) {
 }
~QJsonChannelServiceRepository()
QJsonChannelServiceRepository::~QJsonChannelServiceRepository ()
Definition at line 30 of file QJsonChannelServiceRepository.cpp.
{
 }
Member Function Documentation
addService() [1/2]
bool QJsonChannelServiceRepository::addService (QJsonChannelService * service)
Adds service to the repository.
Parameters
service A service to attach to the repository
Returns
true in case the sevice was added
false in case of failure
Definition at line 38 of file QJsonChannelServiceRepository.cpp.
{
     QByteArray serviceName = service->serviceName ();
     if (serviceName.isEmpty ()) {
         QJsonChannelDebug () << Q_FUNC_INFO << "service added without serviceName classinfo, aborting";
         return false;
     }
     if (d->services.contains (serviceName)) {
         QJsonChannelDebug () << Q_FUNC_INFO << "service with name " << serviceName << " already exist";
         return false;
     }
     service->cacheInvokableInfo ();
     d->services.insert (serviceName, service);
     if (!service->parent ()) {
         d->cleanupHandler.add (service);
     }
     return true;
 }
References QJsonChannelService::serviceName().
Referenced by addService().
addService() [2/2]
bool QJsonChannelServiceRepository::addService (const QByteArray & name, const QByteArray & version, const QByteArray & description, QObject * obj)
Adds service to the repository.
Parameters
name Service name
version Service version
description Service description
obj Service object
Returns
true In case the sevice was added
false In case of failure
Definition at line 33 of file QJsonChannelServiceRepository.cpp.
{
     QJsonChannelService* service = new QJsonChannelService(serviceName, version, description, obj);
     return addService (service);
 }
References addService().
getService()
QJsonChannelService * QJsonChannelServiceRepository::getService (const QByteArray & serviceName)
Return service by name.
Parameters
serviceName a service name to search
Returns
QJsonChannelService* a found sevice
Definition at line 74 of file QJsonChannelServiceRepository.cpp.
{
     if (!d->services.contains (serviceName)) {
         return nullptr;
     }
     return d->services.value (serviceName);
 }
getServiceObject()
QObject * QJsonChannelServiceRepository::getServiceObject (const QByteArray & serviceName)
Return service object by name.
Parameters
serviceName a service name to search
Returns
QJsonChannelService* a found sevice
Definition at line 82 of file QJsonChannelServiceRepository.cpp.
{
     if (!d->services.contains (serviceName)) {
         return nullptr;
     }
     return d->services.value (serviceName)->serviceObj();
 }
removeService() [1/2]
bool QJsonChannelServiceRepository::removeService (QJsonChannelService * service)
Removes service from the repository.
Parameters
service A service to remove from the repository
Returns
true in case the sevice was removed
false in case of failure
Definition at line 58 of file QJsonChannelServiceRepository.cpp.
{
     QByteArray serviceName = service->serviceName ();
     return removeService (serviceName);
 }
References QJsonChannelService::serviceName().
removeService() [2/2]
bool QJsonChannelServiceRepository::removeService (const QByteArray & serviceName)
Removes service from the repository.
Parameters
serviceName A service name to remove from the repository
Returns
true in case the sevice was removed
false in case of failure
Definition at line 63 of file QJsonChannelServiceRepository.cpp.
{
     if (!d->services.contains (serviceName)) {
         QJsonChannelDebug () << Q_FUNC_INFO << "can not find service with name " << serviceName;
         return false;
     }
     d->cleanupHandler.remove (d->services.value (serviceName));
     d->services.remove (serviceName);
     return true;
 }
processMessage()
QJsonChannelMessage QJsonChannelServiceRepository::processMessage (const QJsonChannelMessage & message)
Process a JSON-RPC message. In general it means the invogation of a requested function of a requested service.
Parameters
message JSON-RPC message
Returns
QJsonChannelMessage JSON-RPC response message
Definition at line 90 of file QJsonChannelServiceRepository.cpp.
{
     switch (message.type ()) {
     case QJsonChannelMessage::Init: {
         QJsonChannelMessage response = message.createResponse (d->servicesInfo ());
         return response;
     }
     case QJsonChannelMessage::Request:
     case QJsonChannelMessage::Notification: {
         //
         QByteArray serviceName = message.serviceName().toLatin1 ();
         if (serviceName.isEmpty () || !d->services.contains (serviceName)) {
             if (message.type () == QJsonChannelMessage::Request) {
                 QJsonChannelMessage error =
                     message.createErrorResponse (QJsonChannel::MethodNotFound, QString ("service '%1' not found").arg (serviceName.constData ()));
                 return error;
             }
         } else {
             QJsonChannelService* service  = d->services.value (serviceName);
             QJsonChannelMessage  response = service->dispatch (message);
             return response;
         }
     } break;
     case QJsonChannelMessage::Response:
         // we don't handle responses in the provider
         return QJsonChannelMessage ();
         break;
     default: {
         QJsonChannelMessage error = message.createErrorResponse (QJsonChannel::InvalidRequest, QString ("invalid request"));
         return error;
         break;
     }
     };
     return QJsonChannelMessage ();
 }
References QJsonChannelMessage::createErrorResponse(), QJsonChannelMessage::createResponse(), QJsonChannelMessage::Init, QJsonChannel::InvalidRequest, QJsonChannel::MethodNotFound, QJsonChannelMessage::Notification, QJsonChannelMessage::Request, QJsonChannelMessage::Response, QJsonChannelMessage::serviceName(), and QJsonChannelMessage::type().
The documentation for this class was generated from the following files:
src/QJsonChannelServiceRepository.h
src/QJsonChannelServiceRepository.cpp