QJsonChannel: QJsonChannelMessage Class Reference
QJsonChannelMessage Class Reference
#include <QJsonChannelMessage.h>
Public Types
enum Type {
Invalid, Request, Response, Notification,
Error, Init
}
Public Member Functions
QJsonChannelMessage ()
QJsonChannelMessage (const QJsonChannelMessage &other)
QJsonChannelMessage & operator= (const QJsonChannelMessage &other)
~QJsonChannelMessage ()
void swap (QJsonChannelMessage &other)
QJsonChannelMessage createResponse (const QJsonValue &result) const
QJsonChannelMessage createErrorResponse (QJsonChannel::ErrorCode code, const QString &message=QString(), const QJsonValue &data=QJsonValue()) const
QJsonChannelMessage::Type type () const
bool isValid () const
int id () const
QString serviceName () const
QString method () const
QJsonValue params () const
QJsonValue result () const
int errorCode () const
QString errorMessage () const
QJsonValue errorData () const
QJsonObject toObject () const
QByteArray toJson () const
bool operator== (const QJsonChannelMessage &message) const
bool operator!= (const QJsonChannelMessage &message) const
Static Public Member Functions
static QJsonChannelMessage createRequest (const QString &method, const QJsonArray &params=QJsonArray())
static QJsonChannelMessage createRequest (const QString &method, const QJsonValue &param)
static QJsonChannelMessage createRequest (const QString &method, const QJsonObject &namedParameters)
static QJsonChannelMessage createNotification (const QString &method, const QJsonArray &params=QJsonArray())
static QJsonChannelMessage createNotification (const QString &method, const QJsonValue &param)
static QJsonChannelMessage createNotification (const QString &method, const QJsonObject &namedParameters)
static QJsonChannelMessage fromObject (const QJsonObject &object)
static QJsonChannelMessage fromJson (const QByteArray &data)
Detailed Description
Definition at line 13 of file QJsonChannelMessage.h.
Member Enumeration Documentation
Type
enum QJsonChannelMessage::Type
Enumerator
Invalid
Request
Response
Notification
Error
Init
Definition at line 24 of file QJsonChannelMessage.h.
 { Invalid, Request, Response, Notification, Error, Init };
Constructor & Destructor Documentation
QJsonChannelMessage() [1/2]
QJsonChannelMessage::QJsonChannelMessage ()
Definition at line 68 of file QJsonChannelMessage.cpp.
     : d(new QJsonChannelMessagePrivate)
 {
     d->object.reset(new QJsonObject);
 }
QJsonChannelMessage() [2/2]
QJsonChannelMessage::QJsonChannelMessage (const QJsonChannelMessage & other)
Definition at line 74 of file QJsonChannelMessage.cpp.
     : d(other.d)
 {
 }
~QJsonChannelMessage()
QJsonChannelMessage::~QJsonChannelMessage ()
Definition at line 79 of file QJsonChannelMessage.cpp.
 {
 }
Member Function Documentation
operator=()
QJsonChannelMessage & QJsonChannelMessage::operator= (const QJsonChannelMessage & other)
Definition at line 83 of file QJsonChannelMessage.cpp.
 {
     d = other.d;
     return *this;
 }
swap()
void QJsonChannelMessage::swap (QJsonChannelMessage & other) inline
Definition at line 20 of file QJsonChannelMessage.h.
{
         qSwap (d, other.d);
     }
createRequest() [1/3]
QJsonChannelMessage QJsonChannelMessage::createRequest (const QString & method, const QJsonArray & params = QJsonArray ()) static
Definition at line 188 of file QJsonChannelMessage.cpp.
 {
     QJsonChannelMessage request = QJsonChannelMessagePrivate::createBasicRequest(method, params);
     request.d->type = QJsonChannelMessage::Request;
     QJsonChannelMessagePrivate::uniqueRequestCounter++;
     request.d->object->insert(QLatin1String("id"), QJsonChannelMessagePrivate::uniqueRequestCounter);
     return request;
 }
References method(), params(), and Request.
Referenced by createRequest().
createRequest() [2/3]
QJsonChannelMessage QJsonChannelMessage::createRequest (const QString & method, const QJsonValue & param) static
Definition at line 197 of file QJsonChannelMessage.cpp.
 {
     QJsonArray params;
     params.append(param);
     return createRequest(method, params);
 }
References createRequest(), method(), and params().
createRequest() [3/3]
QJsonChannelMessage QJsonChannelMessage::createRequest (const QString & method, const QJsonObject & namedParameters) static
Definition at line 204 of file QJsonChannelMessage.cpp.
 {
     QJsonChannelMessage request =
         QJsonChannelMessagePrivate::createBasicRequest(method, namedParameters);
     request.d->type = QJsonChannelMessage::Request;
     QJsonChannelMessagePrivate::uniqueRequestCounter++;
     request.d->object->insert(QLatin1String("id"), QJsonChannelMessagePrivate::uniqueRequestCounter);
     return request;
 }
References method(), and Request.
createNotification() [1/3]
QJsonChannelMessage QJsonChannelMessage::createNotification (const QString & method, const QJsonArray & params = QJsonArray ()) static
Definition at line 215 of file QJsonChannelMessage.cpp.
 {
     QJsonChannelMessage notification = QJsonChannelMessagePrivate::createBasicRequest(method, params);
     notification.d->type = QJsonChannelMessage::Notification;
     return notification;
 }
References method(), Notification, and params().
Referenced by createNotification().
createNotification() [2/3]
QJsonChannelMessage QJsonChannelMessage::createNotification (const QString & method, const QJsonValue & param) static
Definition at line 222 of file QJsonChannelMessage.cpp.
 {
     QJsonArray params;
     params.append(param);
     return createNotification(method, params);
 }
References createNotification(), method(), and params().
createNotification() [3/3]
QJsonChannelMessage QJsonChannelMessage::createNotification (const QString & method, const QJsonObject & namedParameters) static
Definition at line 229 of file QJsonChannelMessage.cpp.
 {
     QJsonChannelMessage notification =
         QJsonChannelMessagePrivate::createBasicRequest(method, namedParameters);
     notification.d->type = QJsonChannelMessage::Notification;
     return notification;
 }
References method(), and Notification.
createResponse()
QJsonChannelMessage QJsonChannelMessage::createResponse (const QJsonValue & result) const
Definition at line 238 of file QJsonChannelMessage.cpp.
 {
     QJsonChannelMessage response;
     if (d->object->contains(QLatin1String("id"))) {
         QJsonObject *object = response.d->object.data();
         object->insert(QLatin1String("jsonrpc"), QLatin1String("2.0"));
         object->insert(QLatin1String("id"), d->object->value(QLatin1String("id")));
         object->insert(QLatin1String("result"), result);
         response.d->type = QJsonChannelMessage::Response;
     }
     return response;
 }
References Response, and result().
Referenced by QJsonChannelServiceRepository::processMessage().
createErrorResponse()
QJsonChannelMessage QJsonChannelMessage::createErrorResponse (QJsonChannel::ErrorCode code, const QString & message = QString (), const QJsonValue & data = QJsonValue ()) const
Definition at line 252 of file QJsonChannelMessage.cpp.
 {
     QJsonChannelMessage response;
     QJsonObject error;
     error.insert(QLatin1String("code"), code);
     if (!message.isEmpty())
         error.insert(QLatin1String("message"), message);
     if (!data.isUndefined())
         error.insert(QLatin1String("data"), data);
     response.d->type = QJsonChannelMessage::Error;
     QJsonObject *object = response.d->object.data();
     object->insert(QLatin1String("jsonrpc"), QLatin1String("2.0"));
     if (d->object->contains(QLatin1String("id")))
         object->insert(QLatin1String("id"), d->object->value(QLatin1String("id")));
     else
         object->insert(QLatin1String("id"), 0);
     object->insert(QLatin1String("error"), error);
     return response;
 }
References Error.
Referenced by QJsonChannelServiceRepository::processMessage().
type()
QJsonChannelMessage::Type QJsonChannelMessage::type () const
Definition at line 162 of file QJsonChannelMessage.cpp.
 {
     return d->type;
 }
Referenced by operator<<(), operator==(), and QJsonChannelServiceRepository::processMessage().
isValid()
bool QJsonChannelMessage::isValid () const
Definition at line 157 of file QJsonChannelMessage.cpp.
 {
     return d->type != QJsonChannelMessage::Invalid;
 }
References Invalid.
id()
int QJsonChannelMessage::id () const
Definition at line 275 of file QJsonChannelMessage.cpp.
 {
     if (d->type == QJsonChannelMessage::Notification || !d->object)
         return -1;
     const QJsonValue &value = d->object->value(QLatin1String("id"));
     if (value.isString())
         return value.toString().toInt();
     return value.toInt();
 }
References Notification.
Referenced by operator<<(), and operator==().
serviceName()
QString QJsonChannelMessage::serviceName () const
Definition at line 294 of file QJsonChannelMessage.cpp.
 {
     return method().section(".", 0, -2);
 }
References method().
Referenced by QJsonChannelServiceRepository::processMessage().
method()
QString QJsonChannelMessage::method () const
Definition at line 286 of file QJsonChannelMessage.cpp.
 {
     if (d->type == QJsonChannelMessage::Response || !d->object)
         return QString();
     return d->object->value(QLatin1String("method")).toString();
 }
References Response.
Referenced by createNotification(), createRequest(), methodName(), operator<<(), operator==(), and serviceName().
params()
QJsonValue QJsonChannelMessage::params () const
Definition at line 299 of file QJsonChannelMessage.cpp.
 {
     if (d->type == QJsonChannelMessage::Response || d->type == QJsonChannelMessage::Error)
         return QJsonValue(QJsonValue::Undefined);
     if (!d->object)
         return QJsonValue(QJsonValue::Undefined);
     return d->object->value(QLatin1String("params"));
 }
References Error, and Response.
Referenced by createNotification(), createRequest(), operator<<(), and operator==().
result()
QJsonValue QJsonChannelMessage::result () const
Definition at line 309 of file QJsonChannelMessage.cpp.
 {
     if (d->type != QJsonChannelMessage::Response || !d->object)
         return QJsonValue(QJsonValue::Undefined);
     return d->object->value(QLatin1String("result"));
 }
References Response.
Referenced by createResponse(), fromJson(), fromObject(), and operator<<().
errorCode()
int QJsonChannelMessage::errorCode () const
Definition at line 317 of file QJsonChannelMessage.cpp.
 {
     if (d->type != QJsonChannelMessage::Error || !d->object)
         return 0;
     QJsonObject error =
         d->object->value(QLatin1String("error")).toObject();
     const QJsonValue &value = error.value(QLatin1String("code"));
     if (value.isString())
         return value.toString().toInt();
     return value.toInt();
 }
References Error.
Referenced by operator<<(), and operator==().
errorMessage()
QString QJsonChannelMessage::errorMessage () const
Definition at line 330 of file QJsonChannelMessage.cpp.
 {
     if (d->type != QJsonChannelMessage::Error || !d->object)
         return QString();
     QJsonObject error =
         d->object->value(QLatin1String("error")).toObject();
     return error.value(QLatin1String("message")).toString();
 }
References Error.
Referenced by operator<<(), and operator==().
errorData()
QJsonValue QJsonChannelMessage::errorData () const
Definition at line 340 of file QJsonChannelMessage.cpp.
 {
     if (d->type != QJsonChannelMessage::Error || !d->object)
         return QJsonValue(QJsonValue::Undefined);
     QJsonObject error =
         d->object->value(QLatin1String("error")).toObject();
     return error.value(QLatin1String("data"));
 }
References Error.
Referenced by operator<<(), and operator==().
toObject()
QJsonObject QJsonChannelMessage::toObject () const
Definition at line 140 of file QJsonChannelMessage.cpp.
 {
     if (d->object)
         return QJsonObject(*d->object);
     return QJsonObject();
 }
fromObject()
QJsonChannelMessage QJsonChannelMessage::fromObject (const QJsonObject & object) static
Definition at line 133 of file QJsonChannelMessage.cpp.
 {
     QJsonChannelMessage result;
     result.d->initializeWithObject(message);
     return result;
 }
References result().
toJson()
QByteArray QJsonChannelMessage::toJson () const
Definition at line 147 of file QJsonChannelMessage.cpp.
 {
     if (d->object) {
         QJsonDocument doc(*d->object);
         return doc.toJson();
     }
     return QByteArray();
 }
fromJson()
QJsonChannelMessage QJsonChannelMessage::fromJson (const QByteArray & data) static
Definition at line 114 of file QJsonChannelMessage.cpp.
 {
     QJsonChannelMessage result;
     QJsonParseError error;
     QJsonDocument document = QJsonDocument::fromJson(message, &error);
     if (error.error != QJsonParseError::NoError) {
         QJsonChannelDebug() << Q_FUNC_INFO << error.errorString();
         return result;
     }
     if (!document.isObject()) {
         QJsonChannelDebug() << Q_FUNC_INFO << "invalid message: " << message;
         return result;
     }
     result.d->initializeWithObject(document.object());
     return result;
 }
References QJsonChannel::NoError, and result().
operator==()
bool QJsonChannelMessage::operator== (const QJsonChannelMessage & message) const
Definition at line 89 of file QJsonChannelMessage.cpp.
 {
     if (message.d == d)
         return true;
     if (message.type() == type()) {
         if (message.type() == QJsonChannelMessage::Error) {
             return (message.errorCode() == errorCode() &&
                     message.errorMessage() == errorMessage() &&
                     message.errorData() == errorData());
         } else {
             if (message.type() == QJsonChannelMessage::Notification) {
                 return (message.method() == method() &&
                         message.params() == params());
             } else {
                 return (message.id() == id() &&
                         message.method() == method() &&
                         message.params() == params());
             }
         }
     }
     return false;
 }
References Error, errorCode(), errorData(), errorMessage(), id(), method(), Notification, params(), and type().
operator!=()
bool QJsonChannelMessage::operator!= (const QJsonChannelMessage & message) const inline
Definition at line 61 of file QJsonChannelMessage.h.
{
         return !(operator== (message));
     }
The documentation for this class was generated from the following files:
src/QJsonChannelMessage.h
src/QJsonChannelMessage.cpp