QJsonChannel: QJsonChannelService Class Reference
QJsonChannelService Class Reference
#include <QJsonChannelService.h>
Public Member Functions
QJsonChannelService (const QByteArray &name, const QByteArray &version, const QByteArray &description, QObject *obj, QObject *parent=nullptr)
~QJsonChannelService ()
QObject * serviceObj ()
const QByteArray & serviceName () const
const QJsonObject & serviceInfo () const
const QMetaObject * serviceMetaObject () const
Friends
class QJsonChannelServiceRepository
Detailed Description
Definition at line 10 of file QJsonChannelService.h.
Constructor & Destructor Documentation
QJsonChannelService()
QJsonChannelService::QJsonChannelService (const QByteArray & name, const QByteArray & version, const QByteArray & description, QObject * obj, QObject * parent = nullptr)
Definition at line 144 of file QJsonChannelService.cpp.
     : QObject (parent) {
     d_ptr.reset (new QJsonChannelServicePrivate (this, name, version, description, serviceObj));
 }
References serviceObj().
~QJsonChannelService()
QJsonChannelService::~QJsonChannelService ()
Definition at line 150 of file QJsonChannelService.cpp.
{
 }
Member Function Documentation
serviceObj()
QObject * QJsonChannelService::serviceObj ()
Definition at line 153 of file QJsonChannelService.cpp.
{
     return d_ptr->serviceObj;
 }
Referenced by QJsonChannelService().
serviceName()
const QByteArray & QJsonChannelService::serviceName () const
Definition at line 157 of file QJsonChannelService.cpp.
{
     return d_ptr->serviceName;
 }
Referenced by QJsonChannelServiceRepository::addService(), and QJsonChannelServiceRepository::removeService().
serviceInfo()
const QJsonObject & QJsonChannelService::serviceInfo () const
Definition at line 161 of file QJsonChannelService.cpp.
{
     return d_ptr->serviceInfo;
 }
serviceMetaObject()
const QMetaObject * QJsonChannelService::serviceMetaObject () const
Definition at line 165 of file QJsonChannelService.cpp.
{
     return d_ptr->serviceObj->metaObject ();
 }
Friends And Related Function Documentation
QJsonChannelServiceRepository
friend class QJsonChannelServiceRepository friend
Definition at line 33 of file QJsonChannelService.h.
The documentation for this class was generated from the following files:
src/QJsonChannelService.h
src/QJsonChannelService.cpp