QJsonChannel: src/QJsonChannelMessage.h File Reference
QJsonChannelMessage.h File Reference
#include <QSharedDataPointer>
#include <QMetaType>
#include <QJsonValue>
#include <QJsonObject>
#include <QJsonArray>
#include "QJsonChannelGlobal.h"
Classes
class QJsonChannelMessage
Functions
QJSONCHANNEL_EXPORT QDebug operator<< (QDebug, const QJsonChannelMessage &)
Function Documentation
operator<<()
QJSONCHANNEL_EXPORT QDebug operator<< (QDebug , const QJsonChannelMessage &)
Definition at line 366 of file QJsonChannelMessage.cpp.
 {
     dbg.nospace() << "QJsonChannelMessage(type=" << msg.type();
     if (msg.type() != QJsonChannelMessage::Notification) {
         dbg.nospace() << ", id=" << msg.id();
     }
     if (msg.type() == QJsonChannelMessage::Request ||
         msg.type() == QJsonChannelMessage::Notification) {
         dbg.nospace() << ", method=" << msg.method()
                       << ", params=" << msg.params();
     } else if (msg.type() == QJsonChannelMessage::Response) {
         dbg.nospace() << ", result=" << msg.result();
     } else if (msg.type() == QJsonChannelMessage::Error) {
         dbg.nospace() << ", code=" << msg.errorCode()
                       << ", message=" << msg.errorMessage()
                       << ", data=" << msg.errorData();
     }
     dbg.nospace() << ")";
     return dbg.space();
 }
References QJsonChannelMessage::Error, QJsonChannelMessage::errorCode(), QJsonChannelMessage::errorData(), QJsonChannelMessage::errorMessage(), QJsonChannelMessage::id(), QJsonChannelMessage::method(), QJsonChannelMessage::Notification, QJsonChannelMessage::params(), QJsonChannelMessage::Request, QJsonChannelMessage::Response, QJsonChannelMessage::result(), and QJsonChannelMessage::type().