QJsonChannel: src/QJsonChannelMessage.cpp File Reference
QJsonChannelMessage.cpp File Reference
#include <QDebug>
#include <QJsonDocument>
#include "QJsonChannelMessage.h"
Functions
static QDebug operator<< (QDebug dbg, QJsonChannelMessage::Type type)
QDebug operator<< (QDebug dbg, const QJsonChannelMessage &msg)
Function Documentation
operator<<() [1/2]
static QDebug operator<< (QDebug dbg, QJsonChannelMessage::Type type) static
Definition at line 350 of file QJsonChannelMessage.cpp.
 {
     switch (type) {
     case QJsonChannelMessage::Request:
         return dbg << "QJsonChannelMessage::Request";
     case QJsonChannelMessage::Response:
         return dbg << "QJsonChannelMessage::Response";
     case QJsonChannelMessage::Notification:
         return dbg << "QJsonChannelMessage::Notification";
     case QJsonChannelMessage::Error:
         return dbg << "QJsonChannelMessage::Error";
     default:
         return dbg << "QJsonChannelMessage::Invalid";
     }
 }
References QJsonChannelMessage::Error, QJsonChannelMessage::Notification, QJsonChannelMessage::Request, and QJsonChannelMessage::Response.
operator<<() [2/2]
QDebug operator<< (QDebug dbg, const QJsonChannelMessage & msg)
Definition at line 366 of file QJsonChannelMessage.cpp.
 {
     dbg.nospace() << "QJsonChannelMessage(type=" << msg.type();
     if (msg.type() != QJsonChannelMessage::Notification) {
         dbg.nospace() << ", id=" << msg.id();
     }
     if (msg.type() == QJsonChannelMessage::Request ||
         msg.type() == QJsonChannelMessage::Notification) {
         dbg.nospace() << ", method=" << msg.method()
                       << ", params=" << msg.params();
     } else if (msg.type() == QJsonChannelMessage::Response) {
         dbg.nospace() << ", result=" << msg.result();
     } else if (msg.type() == QJsonChannelMessage::Error) {
         dbg.nospace() << ", code=" << msg.errorCode()
                       << ", message=" << msg.errorMessage()
                       << ", data=" << msg.errorData();
     }
     dbg.nospace() << ")";
     return dbg.space();
 }
References QJsonChannelMessage::Error, QJsonChannelMessage::errorCode(), QJsonChannelMessage::errorData(), QJsonChannelMessage::errorMessage(), QJsonChannelMessage::id(), QJsonChannelMessage::method(), QJsonChannelMessage::Notification, QJsonChannelMessage::params(), QJsonChannelMessage::Request, QJsonChannelMessage::Response, QJsonChannelMessage::result(), and QJsonChannelMessage::type().