QJsonChannel: src/QJsonChannelService.cpp File Reference
QJsonChannelService.cpp File Reference
#include <QVarLengthArray>
#include <QMetaMethod>
#include <QDebug>
#include <QHash>
#include <QPointer>
#include <QStringList>
#include "QJsonChannelService.h"
Functions
QString convertToString (QJsonValue::Type t)
QJsonObject createParameterDescription (const QString &desc, int type)
static bool jsParameterCompare (const QJsonArray &parameters, const QJsonChannelServicePrivate::MethodInfo &info)
static bool jsParameterCompare (const QJsonObject &parameters, const QJsonChannelServicePrivate::MethodInfo &info)
static QVariant convertArgument (const QJsonValue &argument, const QJsonChannelServicePrivate::ParameterInfo &info)
static QByteArray methodName (const QJsonChannelMessage &request)
Function Documentation
convertToString()
QString convertToString (QJsonValue::Type t)
Definition at line 169 of file QJsonChannelService.cpp.
{
     switch (t) {
     case QJsonValue::Null:
         return "null";
     case QJsonValue::Bool:
         return "boolean";
     case QJsonValue::Double:
         return "number";
     case QJsonValue::String:
         return "string";
     case QJsonValue::Array:
         return "array";
     case QJsonValue::Object:
         return "object";
     case QJsonValue::Undefined:
     default:
         return "undefined";
     }
 }
Referenced by createParameterDescription().
createParameterDescription()
QJsonObject createParameterDescription (const QString & desc, int type)
Definition at line 189 of file QJsonChannelService.cpp.
{
     QJsonObject param;
     param["description"] = desc;
     param["type"]        = convertToString (QJsonValue::Type (type));
     //desc["default"] = type;
     return param;
 }
References convertToString().
jsParameterCompare() [1/2]
static bool jsParameterCompare (const QJsonArray & parameters, const QJsonChannelServicePrivate::MethodInfo & info) static
Definition at line 299 of file QJsonChannelService.cpp.
{
     int j = 0;
     for (int i = 0; i < info.parameters.size () && j < parameters.size (); ++i) {
         int jsType = info.parameters.at (i).jsType;
         if (jsType != QJsonValue::Undefined && jsType != parameters.at (j).type ()) {
             if (!info.parameters.at (i).out)
                 return false;
         } else {
             ++j;
         }
     }
     return (j == parameters.size ());
 }
jsParameterCompare() [2/2]
static bool jsParameterCompare (const QJsonObject & parameters, const QJsonChannelServicePrivate::MethodInfo & info) static
Definition at line 314 of file QJsonChannelService.cpp.
{
     for (int i = 0; i < info.parameters.size (); ++i) {
         int        jsType = info.parameters.at (i).jsType;
         QJsonValue value  = parameters.value (info.parameters.at (i).name);
         if (value == QJsonValue::Undefined) {
             if (!info.parameters.at (i).out)
                 return false;
         } else if (jsType == QJsonValue::Undefined) {
             continue;
         } else if (jsType != value.type ()) {
             return false;
         }
     }
     return true;
 }
convertArgument()
static QVariant convertArgument (const QJsonValue & argument, const QJsonChannelServicePrivate::ParameterInfo & info) inline static
Definition at line 331 of file QJsonChannelService.cpp.
{
     if (argument.isUndefined ())
         return QVariant (info.type, Q_NULLPTR);
     if (info.type == QMetaType::QJsonValue || info.type == QMetaType::QVariant || info.type >= QMetaType::User) {
         if (info.type == QMetaType::QVariant)
             return argument.toVariant ();
         QVariant result (argument);
         if (info.type >= QMetaType::User && result.canConvert (info.type))
             result.convert (info.type);
         return result;
     }
     QVariant result = argument.toVariant ();
     if (result.userType () == info.type || info.type == QMetaType::QVariant) {
         return result;
     } else if (result.canConvert (info.type)) {
         result.convert (info.type);
         return result;
     } else if (info.type < QMetaType::User) {
         // already tried for >= user, this is the last resort
         QVariant result (argument);
         if (result.canConvert (info.type)) {
             result.convert (info.type);
             return result;
         }
     }
     return QVariant ();
 }
methodName()
static QByteArray methodName (const QJsonChannelMessage & request) inline static
Definition at line 390 of file QJsonChannelService.cpp.
{
     const QString& methodPath (request.method ());
     return methodPath.midRef (methodPath.lastIndexOf ('.') + 1).toLatin1 ();
 }
References QJsonChannelMessage::method().